# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Jeoun
paginate:       5
baseurl:        ""
url:            "https://jeoun.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Jeoun
  url:          http://jeoun.github.io/
  email:        ''

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/jeoun/jeoun.github.io

# Gems
plugins:
  - jekyll-paginate
